Most likely fix Slimefun-Addon-Community/Galactifun#70
Mooy1/InfinityLib pull request #4
Opened 2021-09-16 18:13 UTC by Seggan

## Description

Fix a NPE in Galactifun

## Code Changes

Added a null check before registering item

## Related Issues

## Checklist

- [ ] I have also tested the proposed changes with an addon.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I have added sufficient Unit Tests to cover my code.
- [x] I updated the version in pom.xml according to semantic versioning.

2021-09-16 23:56 UTC, Mooy1 commented
Tests failed, also when would either one be null? its only called by SlimefunItem which prevents both things from being null

2021-09-17 00:00 UTC, Seggan commented
/shrug biscuit said it was due to us blindly registering recipes with null elements

2021-09-17 00:02 UTC, Seggan commented
See https://pastebin.com/zmRgEx5b

2021-09-17 02:49 UTC, Mooy1 requested changes

2021-09-17 02:49 UTC, Mooy1 commented on src/main/java/io/github/mooy1/infinitylib/machines/MachineRecipeType.java
> +import org.apache.commons.lang.Validate;
unused import

2021-09-17 16:02 UTC, merged